import type { Metadata } from "next";
import { Bebas_Neue } from "next/font/google";
import { ClerkProvider, UserButton } from "@clerk/nextjs";

import "./globals.css";

const bebas_neue = Bebas_Neue({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-bebas-neue",
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${bebas_neue.variable} bg-background`}>
          <div className="absolute right-4 top-4">
            <UserButton />
          </div>
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
